### ISSUE TITLE
Have you found any good learning resources? Please contribute them in to the readme.md

### ISSUE THREAD

**Issue by eync** [eync/Learning-resources#1]
Do you know any good learning resources (which you have experience from)? If u do please contribute it, the categories I am looking for are following: Javascript, Typescript, React, Vuejs, Mongodb, Challenges(coding challenges, coding ideas or project ideas).

**Comment by typg93** [comment]
freecodecamp has a nice interactive JS course that covers the fundamentals as well some of the JS frameworks

for me, I find leetcode and hackerrank are a good place for coding challenges. Want me to add these to the readme?
